on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 6"
  push:
    paths:
      - kali/**

env:
  REGISTRY: ghcr.io
  DST: ghcr.io/${{ github.repository }}/kali:latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kali:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ${{ env.REGISTRY }} as ${{ github.actor }}
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push the image to ${{ env.DST }}
        uses: docker/build-push-action@v5
        with:
          context: kali
          push: true
          tags: ${{ env.DST }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
